api_key: "AIzaSyDSDZPhkF2a0dlwbeyFw30DmJca-pEit2o"
video_url: [
            "https://www.youtube.com/live/Abg8maIN2zg",
            "https://www.youtube.com/live/dd7LhT_jtVo",
            "https://www.youtube.com/watch?v=_Q9XInVZxJU"
]

max_comments: 500
keywords : {
    "andika_hendi": [
                    "andika", 
                    "hendrar", 
                    "hendi", 
                    "perkasa",
                    "tni",
                    "1",
                    "satu",
                    "pdi",
                    "banteng",
                    "rambo",
                    "andhika",
                    "pacul",
                    "loreng",
                    "bintang 4",
                    "hendy",
                    "mega"
                    ],
    "luthfi_taj": [
                    "luthfi", 
                    "taj", 
                    "yasin", 
                    "maimoen",
                    "lutfi",
                    "2",
                    "dua",
                    "polisi",
                    "jokowi",
                    "prabowo",
                    "kim",
                    "mulyono",
                    "bintang 3",
                    "jkw",
                    "coklat",
                    "gus",
                    "solo",                                       
                ]
}

SENTIMENT_DICTIONARY : {
    "positif": [
        "amazing", "awesome", "great", "love", "fantastic", "excellent",
        "visioner", "berpengalaman", "tegas", "merakyat", 
        "integritas", "profesional", "kompeten", "berintegritas", 
        "dekat dengan rakyat", "berjiwa pemimpin","bisa di percaya","andika ye","jateng perkasa","tertarik","mantap"
    ],
    "negatif": [
        "terrible", "hate", "bad", "awful", "poor", "worst",
        "tidak kompeten", "korup", "arogan", "tidak berpengalaman",
        "pembohong", "tidak tegas", "tidak peduli", "egois",
        "lemah", "buruk", "curang"
    ],
    "netral": [
        "standar", "cukup", "biasa saja", "netral", 
        "umum", "lumayan", "tidak buruk", "tidak luar biasa"
    ]
}
