
# append additional stopword
list_stopwords_additional = [  'yg', 'dg', 'rt', 'dgn', 'ny', 'd', 'klo', 
                    'kalo', 'amp', 'biar', 'bikin', 'bilang', 
                    'gak', 'ga', 'krn', 'nya', 'nih', 'sih', 
                    'si', 'tau', 'tdk', 'tuh', 'utk', 'ya', 
                    'jd', 'jgn', 'sdh', 'aja', 'n', 't', 
                    'nyg', 'hehe', 'pen', 'u', 'nan', 'loh', 'rt',
                    '&amp', 'yah', 'bisnis', 'pandemi', 'indonesia',
                    'assalamualaikum', 'warahmatullahi', 'wabarakatuh', 'salam', 'sejahtera', 
                    'untuk', 'kita', 'sekalian', 'shalom', 'um', 'swastiastu',"santi","namu","yangmulia","dr","saudarasaudara","sodarasodara","prof"
                    
                ]


slang_to_formal= {
                "parti":"partai",
                "aja": "saja",
                "adlh": "adalah",
                "akn": "akan",
                "aku": "saya",
                "amiiiin": "amin",
                "and": "dan",
                "anda": "kamu",
                "ane": "saya",
                "ap": "apa",
                "aps": "apa",
                "aq": "saya",
                "prodem": "pro demokrasi",
                "seenggak": "setidak",
                "benernya": "benarnya",
                "bener": "benar",
                "bag": "bagian",
                "sblmnya": "sebelumnya",
                "beud": "sangat",
                "gmn": "gimana",
                "bgmn": "bagaimana",
                "bkan": "bukan",
                "bl": "bila",
                "blg": "bilang",
                "blh": "boleh",
                "bnyak": "banyak",
                "blm": "belum",
                "blom": "belum",
                "blum": "belum",
                "bs": "bisa",
                "bsa": "bisa",
                "krja": "kerja",
                "byk": "banyak",
                "bnyk": "banyak",
                "bsk": "besok",
                "cb": "coba",
                "cm": "hanya",
                "cma": "hanya",
                "cuma": "hanya",
                "d": "di",
                "dngn": "dengan",
                "dg": "dengan",
                "demen": "suka",
                "dasyat": "dahsyat",
                "dgn": "dengan",
                "dlam": "dalam",
                "dlm": "dalam",
                "dn": "dan",
                "dng": "dengan",
                "dpt": "dapat",
                "dr": "dari",
                "dsar": "dasar",
                "dy": "dia",
                "dya": "dia",
                "en": "dan",
                "nggak": "tidak",
                "enggak": "tidak",
                "adem ayem": "tenang",
                "adem": "tenang",
                "ente": "kamu",
                "gimana": "bagaimana",
                "gemana": "gimana",
                "g": "tidak",
                "ga": "tidak",
                "gak": "tidak",
                "gitu": "begitu",
                "gk": "tidak",
                "gt": "begitu",
                "tau": "tahu",
                "gtau": "tidak tahu",
                "gua": "saya",
                "gub": "gubernur",
                "die": "dia",
                "diemen": "diam",
                "gue": "aku",
                "gw": "saya",
                "hy": "hanya",
                "hny": "hanya",
                "hr": "hari",
                "hrus": "harus",
                "insaallah": "insyaa allah",
                "insallah": "insyaa allah",
                "insyaallah": "insyaa allah",
                "insyallah": "insyaa allah",
                "iy": "iya",
                "iye": "iya",
                "jd": "jadi",
                "jdi": "jadi",
                "jg": "juga",
                "jga": "juga",
                "jgn": "jangan",
                "jkwi": "jokowi",
                "w": "saya",
                "jkw": "jokowi",
                "pke": "pakai",
                "mncul": "muncul",
                "jk": "jusuf kalla",
                "jlas": "jelas",
                "jlek": "jelek",
                "jls": "jelas",
                "jng": "jangan",
                "Kalopun": "kalau pun",
                "jongosnya": "pelayannya",
                "gawean": "kerja",
                "ktahuan": "ketahuan",
                "kalo": "kalaupun",
                "karna": "karena",
                "kau": "kamu",
                "seenggaknya": "setidaknya",
                "ngakunya": "mengakunya",
                "ngaku": "mengaku",
                "kl": "kalau",
                "ksh": "kasih",
                "klh": "kalah",
                "klo": "kalau",
                "klu": "kalau",
                "klw": "kalau",
                "km": "kamu",
                "knapa": "kenapa",
                "ko": "kok",
                "kog": "kok",
                "koq": "kok",
                "kpada": "kepada",
                "kpd": "kepada",
                "kpn": "kapan",
            }
